trigger:
- main

name: Deploy Bicep files

# parameters:
#   azureServiceConnection: 'bicepserviceconnection'

variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'azmonitortest'
  location: 'East US'
  bicepParamFile: './moduleparam.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '677e2958-8c03-4ec0-9cb2-a8f3d7a4b5ec'
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --parameters $(bicepParamFile) `
        --name DeployPipelineTemplate