trigger:
- main

name: Deploy Bicep files

parameters:
  azureServiceConnection: 'bicepserviceconnection'

variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'azmonitortest'
  location: 'East US'
  bicepParamFile: './moduleparam.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.azureServiceConnection }}'
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group create `
        --resource-group $(resourceGroupName) `
        --parameters $(bicepParamFile) `
        --name DeployPipelineTemplate